### ISSUE TITLE
更改 aliases.yml 格式

### ISSUE THREAD

**Issue by trustgit** [trustgit/nodebot#24]
因为无序数组的查找速度为 `O(n)` :
```yaml
- from: '-'
  to: '-rec me'
- from: '--'
  to: '-stat me'
```
而如下散列表（对象）格式的查找速度为 `O(1)`，且更简洁:
```yaml
'-': '-rec me'
'--': '-stat me'
```
